<?php

/**
 * PlugintFeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugintFeedbackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlugintFeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlugintFeedback');
    }
}